Vagrant.configure("2") do |config|
  config.vm.box = "perk/ubuntu-2204-arm64"
  config.vm.hostname = "kelompok-C13"
  config.vm.network "forwarded_port" , guest: 80, host: 8080
  config.vm.synced_folder ".", "/vagrant", type: "smb", smb_host: "192.168.1.2"
  config.vm.provider "qemu" do |qemu| 
     qemu.memory = 2048
     qemu.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "webapp.yml"
  end  
 end
 
